//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enigma {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Enigma.bin.Debug.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But then he must have arguments.\nPress any key....
        /// </summary>
        public static string notArgument {
            get {
                return ResourceManager.GetString("notArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I do not know this encryption algorithm :(\nPress any key....
        /// </summary>
        public static string wrongAlgorithm {
            get {
                return ResourceManager.GetString("wrongAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To decrypt, you must enter the 4 parameters: the name of the file that you are going to decipher (*.bin), the name of the algorithm (aes, des, rc2 or rijndael), file name with a key (*.txt) and the name of the output file.\nPress any key....
        /// </summary>
        public static string wrongDecrypt {
            get {
                return ResourceManager.GetString("wrongDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To encrypt, you must enter 3 paramters: the name of the file that are going to encrypt, encryption algorithm name (aes, des, rc2 or rijndael) and the name of the output file (*.bin).\nPress any key....
        /// </summary>
        public static string wrongEncrypt {
            get {
                return ResourceManager.GetString("wrongEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to say what you want: to encode or decode the information. Use keywords: encryp or decrypt.\nTo encrypt, you must enter 3 paramters: the name of the file that are going to encrypt, encryption algorithm name (aes, des, rc2 or rijndael) and the name of the output file (*.bin).\nTo decrypt, you must enter the 4 parameters: the name of the file that you are going to decipher (*.bin), the name of the algorithm (aes, des, rc2 or rijndael), file name with a key (*.txt) and the name of the output file.\nPr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wrongKeyword {
            get {
                return ResourceManager.GetString("wrongKeyword", resourceCulture);
            }
        }
    }
}
